[package]
name = "git-bump"
version = "0.0.0"
authors = ["buck <buckhx@gmail.com>"]

[dependencies.clap]
version = "2"
features = ["suggestions", "color", "wrap_help", "yaml"]

[dependencies]
git2 = "0.6"
regex = "0.1"
lazy_static = "0.2.2"
